### ISSUE TITLE
Sirius returns HTTP 500 for token with grant client_credentials

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#149]
```
                                                                                 v--- HERE!
RuntimeError - Invalid response for https://kosapi.fit.cvut.cz/usermap/v1/people//roles?all=B-00000-ZAMESTNANEC with status 405.:
	/app/lib/sirius_api/umapi_client.rb:48:in `user_has_roles?'
	/app/lib/sirius_api/user.rb:43:in `has_role?'
	/app/lib/sirius_api/user.rb:26:in `student_access_allowed?'
	/app/app/api/events_endpoints.rb:28:in `represent'
	/app/app/api/events_endpoints.rb:116:in `block (4 levels) in <class:EventsEndpoints>'
```

**Comment by jirutka** [comment]
Fixed by https://github.com/cvut/sirius/pull/157.
