### ISSUE TITLE
Planning of paralles fails: lib/sirius/time_converter.rb: undefined method <= for nil:NilClass

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#194]
This time it’s not a temporary error, I’ve reproduced it 4 times during today, it always failed. :(

@flexik, any idea?

```
INFO  [sirius.rake]: Importing students, grab a coffee.
INFO  [sirius.rake]: Planning parallels.
D, [2017-03-27T21:05:25.269593 #561] DEBUG -- sentry: ** [Raven] Sending event b5f573f5eaa5589ac3fd40f7762abedb to Sentry
D, [2017-03-27T21:05:25.393360 #561] DEBUG -- sentry: ** [Raven] Raven HTTP Transport connecting to https://sentry.fit.cvut.cz
rake aborted!
NoMethodError: undefined method `<=' for nil:NilClass
Did you mean?  <=>
/opt/sirius/lib/sirius/time_converter.rb:35:in `convert_time'
/opt/sirius/app/roles/planned_timetable_slot.rb:43:in `generate_teaching_time'
/opt/sirius/app/roles/planned_timetable_slot.rb:12:in `generate_events'
/opt/sirius/lib/sirius/event_planner.rb:20:in `block (2 levels) in plan_semester'
/opt/sirius/lib/sirius/event_planner.rb:19:in `each'
/opt/sirius/lib/sirius/event_planner.rb:19:in `flat_map'
/opt/sirius/lib/sirius/event_planner.rb:19:in `block in plan_semester'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/dataset/actions.rb:147:in `block in each'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:676:in `block (2 levels) in fetch_rows'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:676:in `yield_hash_rows'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:676:in `block in fetch_rows'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:175:in `execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:526:in `_execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:342:in `block (2 levels) in execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:547:in `check_database_errors'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:342:in `block in execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/connecting.rb:280:in `block in synchronize'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/connecting.rb:280:in `synchronize'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:342:in `execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/dataset/actions.rb:1065:in `execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:676:in `fetch_rows'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/dataset/actions.rb:147:in `each'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel_pg-1.6.17/lib/sequel_pg/sequel_pg.rb:62:in `each'
/opt/sirius/lib/sirius/event_planner.rb:17:in `flat_map'
/opt/sirius/lib/sirius/event_planner.rb:17:in `plan_semester'
/opt/sirius/lib/sirius/schedule_manager.rb:19:in `block (2 levels) in plan_stored_parallels'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/transactions.rb:215:in `_transaction'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/transactions.rb:190:in `block in transaction'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/connecting.rb:280:in `block in synchronize'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/connecting.rb:280:in `synchronize'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/transactions.rb:156:in `transaction'
/opt/sirius/lib/sirius/schedule_manager.rb:18:in `block in plan_stored_parallels'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/dataset/actions.rb:147:in `block in each'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:676:in `block (2 levels) in fetch_rows'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:676:in `yield_hash_rows'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:676:in `block in fetch_rows'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:175:in `execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:526:in `_execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:342:in `block (2 levels) in execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:547:in `check_database_errors'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:342:in `block in execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/connecting.rb:280:in `block in synchronize'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/database/connecting.rb:280:in `synchronize'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:342:in `execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/dataset/actions.rb:1065:in `execute'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/adapters/postgres.rb:676:in `fetch_rows'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel-4.42.1/lib/sequel/dataset/actions.rb:147:in `each'
/opt/sirius/vendor/bundle/ruby/2.3.0/gems/sequel_pg-1.6.17/lib/sequel_pg/sequel_pg.rb:62:in `each'
/opt/sirius/lib/sirius/schedule_manager.rb:17:in `plan_stored_parallels'
/opt/sirius/lib/tasks/sirius.rake:34:in `block (3 levels) in <top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => sirius:events => sirius:events:plan
(See full trace by running task with --trace)
```

Related to #192

/cc @jnv

**Comment by jnv** [comment]
SQL log:

```
DEBUG [sql]: (0.000320s) SELECT * FROM "parallels" WHERE "id" = 817147462305
DEBUG [sql]: (0.000138s) SELECT * FROM "courses" WHERE "id" = 'BIK-SQL.1'
DEBUG [sql]: (0.000189s) SELECT * FROM "rooms" WHERE "id" = 'T9:349'
DEBUG [sql]: (0.000437s) SELECT * FROM "events" WHERE (("timetable_slot_id" = 831354859605) AND ("absolute_sequence_number" = 1)) LIMIT 1
DEBUG [sql]: (0.000867s) UPDATE "events" SET "updated_at" = '2017-03-29 17:30:02.028382+0200', "deleted" = true WHERE ("id" = 220060)
DEBUG [sql]: (0.000369s) SELECT * FROM "events" WHERE (("timetable_slot_id" = 831354859605) AND ("absolute_sequence_number" = 2)) LIMIT 1
DEBUG [sql]: (0.000446s) UPDATE "events" SET "updated_at" = '2017-03-29 17:30:02.033443+0200', "deleted" = true WHERE ("id" = 220061)
DEBUG [sql]: (0.000239s) SELECT * FROM "events" WHERE (("timetable_slot_id" = 831354859605) AND ("absolute_sequence_number" = 3)) LIMIT 1
DEBUG [sql]: (0.000312s) UPDATE "events" SET "updated_at" = '2017-03-29 17:30:02.037634+0200', "deleted" = true WHERE ("id" = 220062)
DEBUG [sql]: (0.000380s) SELECT * FROM "events" WHERE (("timetable_slot_id" = 831354859605) AND ("absolute_sequence_number" = 4)) LIMIT 1
DEBUG [sql]: (0.000449s) UPDATE "events" SET "updated_at" = '2017-03-29 17:30:02.041956+0200', "deleted" = true WHERE ("id" = 220063)
DEBUG [sql]: (0.000253s) SELECT * FROM "events" WHERE (("timetable_slot_id" = 831354859605) AND ("absolute_sequence_number" = 5)) LIMIT 1
DEBUG [sql]: (0.000296s) UPDATE "events" SET "updated_at" = '2017-03-29 17:30:02.046133+0200', "deleted" = true WHERE ("id" = 220064)
DEBUG [sql]: (0.000227s) SELECT * FROM "events" WHERE (("timetable_slot_id" = 831354859605) AND ("absolute_sequence_number" = 6)) LIMIT 1
DEBUG [sql]: (0.000533s) UPDATE "events" SET "updated_at" = '2017-03-29 17:30:02.049942+0200', "deleted" = true WHERE ("id" = 220065)
DEBUG [sql]: (0.000353s) SELECT * FROM "events" WHERE (("timetable_slot_id" = 831354859605) AND ("absolute_sequence_number" = 7)) LIMIT 1
DEBUG [sql]: (0.000358s) UPDATE "events" SET "updated_at" = '2017-03-29 17:30:02.054708+0200', "deleted" = true WHERE ("id" = 220066)
DEBUG [sql]: (0.000210s) SELECT * FROM "events" WHERE (("timetable_slot_id" = 831354859605) AND ("deleted" IS FALSE))
DEBUG [sql]: (0.000168s) UPDATE "events" SET "deleted" = true, "applied_schedule_exception_ids" = NULL WHERE (1 = 0)
DEBUG [sql]: (0.000141s) ROLLBACK
```

What seems interesting here is `deleted = true`

**Comment by jnv** [comment]
Okay, BIK, so it is manually inserted course, isn't it? Could we have a collision here?

**Comment by kalvotom** [comment]
@jnv: Yes it is. See [the schedule for part-time students](https://fit.cvut.cz/sites/default/files/Rozvrh-2-r-LS-2016-17.pdf).

**Comment by kalvotom** [comment]
This might be also relevant:

> V letním semestru 2016/17 jsou pro kombinovanou výuku druhého ročníku rozvrhovány tři volitelné předměty: BIK-MEK, BIK-HMI a BIK-SQL.1 (viz tabulka). Tyto tři předměty se v rozvrhu částečně překrývají. ([source](https://fit.cvut.cz/student/kombinovane/rozvrh))

**Comment by jnv** [comment]
This is a data integrity error; there is a `timetable_slot` with `id = 831354861805` which has NULL `duration`.

|id|day|parity|first_hour|duration|parallel_id|created_at|updated_at|room_id|deleted_at|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|831354861805|6|0|1|NULL|817147461505|2017-03-19 20:13:32.778892|2017-03-27 20:03:07.446078|T9:349|NULL|

It is associated with parallel `id = 817147461505` which is BIK-SQL.1.

|id|parallel_type|course_id|code|capacity|occupied|semester|created_at|updated_at|teacher_ids|student_ids|faculty|deleted_at|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|817147461505|lecture|BIK-SQL.1|1|NULL|13|B162|2017-01-26 03:59:34.429214|2017-03-29 11:58:38.622451|{halaska}|{redacted}|18000|NULL|

The question is, how it got into the system; I suppose it was inserted manually, is that correct, @kalvotom?

Either way, I suppose we are missing integrity checks for timetable_slots, i.e. `duration NOT NULL`. Unless there is some other legitimate use case for this, @flexik?

**Comment by kalvotom** [comment]
> The question is, how it got into the system; I suppose it was inserted manually, is that correct, @kalvotom? There may be an error in routine.

Yes, that is correct. I am quite sure Daniel Vašata has some arcane EXCEL script that he uses while creating these part-time events. Maybe it is buggy, I will contact him and ask what he thinks about this.

**Comment by jnv** [comment]
Thanks @kalvotom! On the other hand, we don't have a procedure which creates timetable slots, these should be imported from KOS. Perhaps it is possible to create slot with no duration?

**Comment by kalvotom** [comment]
I am unable to check this right now (Java update is preventing me from running iKOS :-)). However, I do not see any use case for time slots with zero duration...

**Comment by jirutka** [comment]
Timemasters currently can’t create timetable slots, so these must be imported from KOS. We should definitely add validation into importing procedure to skip such invalid data.

**Comment by jirutka** [comment]
Okay, I’ve fixed it in KOSapi. Timetable slot without a day, firstHour or duration is de facto invalid, so KOSapi will not return them since now.

**Comment by jirutka** [comment]
Just for the record, I have to also manually remove 831354861805 from the `timetable_slot` table, then the import process finally succeeded.

Thanks @jnv and @kalvotom for help!

**Comment by vasatdan** [comment]
Ahoj. Rozvrhová okénka, která jsem vytvářel měli id 218509 - 218645. ID 831354861805 do tohodle nezapadá. Navíc já jsem tam vše vytvářel okolo 16.02.2017. Takže se mi to moc nezdá...
